apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
  namespace: boardgame 
spec:
  selector:
    matchLabels:
      app: boardgame
      version: blue
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
        version: blue
    spec:
      containers:
        - name: boardgame
          image: kanalavinodkumar/boardgame:blue # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster


---

# apiVersion: v1 # Kubernetes API version
# kind: Service # Kubernetes resource kind we are creating
# metadata: # Metadata of the resource kind we are creating
#   name: boardgame-ssvc
#   namespace: boardgame
# spec:
#   selector:
#     app: boardgame
#   ports:
#     - protocol: "TCP"
#       port: 8080 # The port that the service is running on in the cluster
#       targetPort: 8080 # The port exposed by the service
#   #type: LoadBalancer # type of the service.
---
kind: Service
apiVersion: v1
metadata: # Metadata of the resource kind we are creating
  name: boardgame-ssvc
  namespace: boardgame
spec:
  selector:
    app: boardgame
  type: NodePort
  ports:
  - name: http-port
    protocol: TCP
    # service-port
    port: 8080
    # pod-port
    targetPort: 8080

