apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: boardgame-deployment
  namespace: boardgame 
spec:
  selector:
    matchLabels:
      app: boardgame
      version: green
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: boardgame
        version: green
    spec:
      containers:
        - name: boardgame
          image: kanalavinodkumar/boardgame:green # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster

